# Generated by Django 5.1.4 on 2024-12-08 22:29

import core.enums.currency
import core.models.flexup_enum_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', core.models.flexup_enum_field.FlexUpEnumField(choices=[('AFN', 'Afghani'), ('DZD', 'Algerian Dinar'), ('ARS', 'Argentine peso'), ('AMD', 'Armenian Dram'), ('AWG', 'Aruban florin'), ('AUD', 'Australian dollar'), ('AZN', 'Azerbaijan Manat'), ('BSD', 'Bahamian dollar'), ('BHD', 'Bahraini Dinar'), ('THB', 'Baht'), ('PAB', 'Balboa'), ('BBD', 'Barbados Dollar'), ('BYN', 'Belarusian ruble'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudian dollar'), ('BOB', 'Boliviano'), ('BRL', 'Brazilian real'), ('BND', 'Brunei dollar'), ('BGN', 'Bulgarian lev'), ('BIF', 'Burundi Franc'), ('CVE', 'Cabo Verde Escudo'), ('CAD', 'Canadian dollar'), ('KYD', 'Cayman Islands Dollar'), ('XOF', 'CFA Franc BCEAO'), ('XAF', 'CFA Franc BEAC'), ('XPF', 'CFP Franc'), ('CLP', 'Chilean peso'), ('CNY', 'Chinese Yuan'), ('COP', 'Colombian peso'), ('KMF', 'Comorian Franc'), ('CDF', 'Congolese franc'), ('BAM', 'Convertible Mark'), ('NIO', 'Cordoba Oro'), ('CRC', 'Costa Rican Colon'), ('HRK', 'Croatia Kuna'), ('CUP', 'Cuban peso'), ('CZK', 'Czech koruna'), ('GMD', 'Dalasi'), ('DKK', 'Danish krone'), ('MKD', 'Denar'), ('DJF', 'Djibouti Franc'), ('STN', 'Dobra'), ('DOP', 'Dominican peso'), ('VND', 'Dong'), ('XCD', 'East Caribbean Dollar'), ('EGP', 'Egyptian pound'), ('SVC', 'El Salvador Colon'), ('ETB', 'Ethiopian Birr'), ('EUR', 'Euro'), ('FKP', 'Falkland Islands pound'), ('FJD', 'Fiji Dollar'), ('SLL', 'First Leone'), ('HUF', 'Forint'), ('GHS', 'Ghana Cedi'), ('GIP', 'Gibraltar Pound'), ('HTG', 'Gourde'), ('PYG', 'Guarani'), ('GGP', 'Guernsey Pound'), ('GNF', 'Guinean Franc'), ('GYD', 'Guyana Dollar'), ('HKD', 'Hong Kong Dollar'), ('UAH', 'Hryvnia'), ('ISK', 'Iceland Krona'), ('INR', 'Indian rupee'), ('IRR', 'Iranian rial'), ('IQD', 'Iraqi Dinar'), ('IMP', 'Isle of Man Pound'), ('JMD', 'Jamaican dollar'), ('JEP', 'Jersey Pound'), ('JOD', 'Jordanian Dinar'), ('KES', 'Kenyan Shilling'), ('PGK', 'Kina'), ('KWD', 'Kuwaiti Dinar'), ('AOA', 'Kwanza'), ('MMK', 'Kyat'), ('LAK', 'Lao kip'), ('GEL', 'Lari'), ('LBP', 'Lebanese pound'), ('ALL', 'Lek'), ('HNL', 'Lempira'), ('LRD', 'Liberian dollar'), ('LYD', 'Libyan Dinar'), ('SZL', 'Lilangeni'), ('LSL', 'Loti'), ('MGA', 'Malagasy Ariary'), ('MWK', 'Malawi Kwacha'), ('MYR', 'Malaysian ringgit'), ('MUR', 'Mauritius Rupee'), ('MXN', 'Mexican peso'), ('MDL', 'Moldovan Leu'), ('MAD', 'Moroccan Dirham'), ('MZN', 'Mozambique Metical'), ('BOV', 'Mvdol'), ('NGN', 'Naira'), ('ERN', 'Nakfa'), ('NAD', 'Namibia Dollar'), ('NPR', 'Nepalese rupee'), ('ANG', 'Netherlands Antillean guilder'), ('ILS', 'New Israeli Sheqel'), ('TWD', 'New Taiwan dollar'), ('NZD', 'New Zealand Dollar'), ('BTN', 'Ngultrum'), ('KPW', 'North Korean won'), ('NOK', 'Norwegian krone'), ('MRU', 'Ouguiya'), ('TOP', 'Pa`anga'), ('PKR', 'Pakistan Rupee'), ('MOP', 'Pataca'), ('UYU', 'Peso Uruguayo'), ('PHP', 'Philippine peso'), ('PLN', 'Polish Złoty'), ('GBP', 'Pound Sterling'), ('BWP', 'Pula'), ('QAR', 'Qatari Rial'), ('GTQ', 'Quetzal'), ('ZAR', 'Rand'), ('OMR', 'Rial Omani'), ('KHR', 'Riel'), ('RON', 'Romanian leu'), ('MVR', 'Rufiyaa'), ('IDR', 'Rupiah'), ('RUB', 'Russian ruble'), ('RWF', 'Rwanda Franc'), ('SHP', 'Saint Helena Pound'), ('SAR', 'Saudi riyal'), ('SLE', 'Second Leone'), ('RSD', 'Serbian dinar'), ('SCR', 'Seychelles Rupee'), ('SGD', 'Singapore Dollar'), ('PEN', 'Sol'), ('SBD', 'Solomon Islands Dollar'), ('KGS', 'Som'), ('SOS', 'Somali shilling'), ('TJS', 'Somoni'), ('SSP', 'South Sudanese Pound'), ('LKR', 'Sri Lanka Rupee'), ('SDG', 'Sudanese Pound'), ('SRD', 'Surinam Dollar'), ('SEK', 'Swedish krona'), ('CHF', 'Swiss franc'), ('SYP', 'Syrian pound'), ('BDT', 'Taka'), ('WST', 'Tala'), ('TZS', 'Tanzanian Shilling'), ('KZT', 'Tenge'), ('TTD', 'Trinidad and Tobago Dollar'), ('MNT', 'Tugrik'), ('TND', 'Tunisian Dinar'), ('TRY', 'Turkish lira'), ('TMT', 'Turkmenistan New Manat'), ('TVD', 'Tuvalu Dollar'), ('AED', 'UAE Dirham'), ('UGX', 'Uganda Shilling'), ('USD', 'US Dollar'), ('UZS', 'Uzbekistan Sum'), ('VUV', 'Vatu'), ('VED', 'Venezuela Bolívar Digital'), ('VEF', 'Venezuela Bolívar Fuerte'), ('VES', 'Venezuela Bolívar Soberano'), ('KRW', 'Won'), ('YER', 'Yemeni rial'), ('JPY', 'Yen'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwe Dollar')], flexup_enum=core.enums.currency.Currency, max_length=3, verbose_name='Currency')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Rate')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
